name: Django EC2 Deploy

on:
  push:
    branches:
      - dev_2_템플릿기반_github_actions_간단배포-2025-05-31
jobs:
  Explore-GitHub-Actions2:
    runs-on: ubuntu-latest 
    
    steps:
      # actions/checkout@v3: 소스코드를 runner에 내려받습니다.
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create remote directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/django-react-nginx-github-actions-hjs-distribute
            mkdir -p /home/ubuntu/django-react-nginx-github-actions-hjs-distribute
