name: Django EC2 Deploy

on:
  push:
    branches:
      - dev_2
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
        
    steps:  
      - name: connect ec2
        uses: appleboy/ssh-action@master  # ssh 접속 라이브러리
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "< requirements.txt installed >"
            echo "< pulled completed >"
            echo "< secrets.json file created >"
